name: vds-mental-health
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - jupyterlab
  - ipykernel
  - statsmodels
  - pyarrow
  - pip:
      - tqdm
